#!/bin/bash

db=${TMSU_DB:-$HOME/.tmsu/default.db}
out=$(mktemp /tmp/tmsu.XXXX.out)
err=$(mktemp /tmp/tmsu.XXXX.err)

function list_all_tags () {
    echo 'select name from tag;' | sqlite3 $db
}

if [ "$1" == 'tag' ]; then
    shift
    files=("$@")
    if [ ! -s $db ]; then
        tag_initial=$(zenity --entry --text "Create your 1st tag:" --entry-text "example.tag");
        tmsu tag --tags "$tag_initial" "${files[@]}" > $out 2> $err
    else
        tags=$(list_all_tags | zenity --list --title="tag" --text="Enter tag(s) to apply" --column=tags --editable --multiple --separator=' ')
        if [ $? -eq 0 -a -n "$tags" ]; then
            tmsu tag --tags "$tags" "${files[@]}" > $out 2> $err
        fi
    fi
    
    ret=$?
    if [[ $ret ]]; then
        txt="Return code: $ret\n\nStderr:\n$(cat $err)\n\nStdout:\n$(cat $out)"
        if [ $ret -gt 0 ]; then
            zenity --warning --text="$txt"
        else
            zenity --info --text="$txt"
        fi
    fi
fi
