#!/bin/bash

db=${TMSU_DB:-$HOME/.tmsu/default.db}
out=$(mktemp /tmp/tmsu.XXXX.out)
err=$(mktemp /tmp/tmsu.XXXX.err)
PWD=$(pwd)

function list_all_tags () {
    echo 'select name from tag;' | sqlite3 $db
}

if [ "$1" == 'tag' ]; then
    shift
    files=("$@")
    if [ ! -s $db ]; then
        tag_initial=$(zenity --width 400 --height 250 --entry --title="gtmsu $db" --text "Create your 1st tag:" --entry-text "example.tag");
        tmsu tag --tags "$tag_initial" "${files[@]}" > $out 2> $err
    else
        tags=$(list_all_tags | zenity --width 400 --height 250 --list --title="gtmsu $db" --text="Enter, edit or create new tag(s)" --column=tags --editable --multiple --separator=' ')
        if [ $? -eq 0 -a -n "$tags" ]; then
            tmsu tag --tags "$tags" "${files[@]}" > $out 2> $err
        fi
    fi
    
    ret=$?
    if [[ $ret ]]; then
        txt="Return code: $ret\n\nStderr:\n$(cat $err)\n\nStdout:\n$(cat $out)"
        if [ $ret -gt 0 ]; then
            zenity --width 400 --height 250 --title="gtmsu $db" --warning --text="$txt"
        #else
        #    zenity --width 400 --height 250 --title="gtmsu $db" --info --text="$txt"
        fi
    fi
elif [ "$1" == 'mount' ]; then
    txt=$(zenity --entry --text "Create a path to where "tags" directory should mount:" --entry-text "/media/truecrypt3/Videos")
    mkdir -p "$txt"
    if [ -d "$txt" ]; then
        tmsu mount "$txt"
        cd "$txt/tags"
        tags_ls=$(ls)
        cd $PWD
        zenity --info --text "Tags successsfully mounted at $txt.\n\n$tags_ls"
    fi
    #
    echo ""
elif [ "$1" == 'edit' ]; then
    #
    echo ""
elif [ "$1" == 'db' ]; then
    #
    echo ""
elif [ "$1" == 'import' ]; then
    zenity --info --text "Browse to your tags.txt\n(a file containing a list of tags, 1 per line)"
    tags_list=$(zenity --file-selection)
    if [ -f "$tags_list" ]; then
        echo "Valid filepath found, continuing..."
        zenity --info --text "This may take a while..."
        file_name=".wee$$"
        touch "$file_name"
        tags_file=$(cat "$tags_list")
        for fn in $tags_file
         do
            tmsu tag "$file_name" $fn
        done
        zenity --info --text "Imported tags: $tags_file"
        rm "$file_name"
    else
        zenity --error --text "Import failed! No such file: $file_name"
    fi
fi

exit 0
